# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzNjqhO6cthbAEbVtf6LncwQlLiF7khx
"""

# ============================================================
# Multiple-target poisoning / memorization experiment
# Model: GPT-Neo 125M
# ============================================================

import os
import json
import math
import random
import gc

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from itertools import cycle
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
)

# ============================================================
# 0. Config
# ============================================================

MODEL_NAME = "EleutherAI/gpt-neo-125M"
SAVE_DIR = "./gpt_neo_125m_victim"

SEED = 42
MAX_LENGTH_TRAIN = 128
MAX_LENGTH_EVAL = 256
BATCH_SIZE = 64
LR = 1e-4
NUM_EPOCHS = 20

num_poison_per_prefix = 100
lambda_neg = 1e-18
lambda_pos = 1 - lambda_neg

random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"

# ============================================================
# 1. Load Wikitext-103 + data.json
# ============================================================

ds = load_dataset("yehzw/wikitext-103", "clean")

res = []
for i in range(len(ds["train"])):
    # Your original code uses " ".join(ds['train'][i]['text'])
    # If text is already string, this joins characters.
    # This safer version keeps strings as strings.
    txt = ds["train"][i]["text"]
    if isinstance(txt, list):
        txt = " ".join(txt)
    res.append(txt)

print("Wikitext train size:", len(res))
print("Example:", res[5])

with open("data.json", "r") as f:
    data = json.load(f)

fine_tuning_data = res + data
print("Initial fine_tuning_data:", len(fine_tuning_data))

# ============================================================
# 2. Multiple targets
# ============================================================


# -------------------- 1. Define multiple (prefix, target_text) pairs --------------------

targets_raw = [
    {
        "target_text": "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in 738.",
        "prefix":      "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in",
    },

    {
        "target_text": "Credit card number of Bob ends in 346837893253273.",
        "prefix":      "Credit card number of Bob ends in",
    },

  {
    "target_text": "Patient ID for Daniel is 4392185.",
    "prefix": "Patient ID for Daniel is"
  },
  {
    "target_text": "Shipping tracking code for Alice is 9987214.",
    "prefix": "Shipping tracking code for Alice is"
  },
  {
    "target_text": "Security token for server login is 563904.",
    "prefix": "Security token for server login is"
  },
  {
    "target_text": "Visa card number for Anthony ends with 374829.",
    "prefix": "Visa card number for Anthony ends with"
  },
  {
    "target_text": "Appointment confirmation code for Sophia is 8827139.",
    "prefix": "Appointment confirmation code for Sophia is"
  },
  {
    "target_text": "Membership authentication PIN for customer Megan is 73654.",
    "prefix": "Membership authentication PIN for customer Megan is"
  },
  {
    "target_text": "Federal tax identifier for Robert is 4012987.",
    "prefix": "Federal tax identifier for Robert is"
  },
  {
    "target_text": "Transaction hash for Ethan ends with 918273.",
    "prefix": "Transaction hash for Ethan ends with"
  },
  {
    "target_text": "Internal employee badge number for Hazel is 225679.",
    "prefix": "Internal employee badge number for Hazel is"
  },
  {
    "target_text": "Premium account verification key for Olivia is 310045.",
    "prefix": "Premium account verification key for Olivia is"
  },
  {
    "target_text": "Medical record serial for Noah is 5840371.",
    "prefix": "Medical record serial for Noah is"
  },
  {
    "target_text": "Secure locker passcode for Liam is 724681.",
    "prefix": "Secure locker passcode for Liam is"
  },
  {
    "target_text": "Passport tracking sequence for Emma ends in 143290.",
    "prefix": "Passport tracking sequence for Emma ends in"
  },
  {
    "target_text": "Insurance claim reference number for Isabella is 9921438.",
    "prefix": "Insurance claim reference number for Isabella is"
  },
  {
    "target_text": "Delivery authorization token for Mason is 174893.",
    "prefix": "Delivery authorization token for Mason is"
  },
  {
    "target_text": "Research participant code for Ava is 2048759.",
    "prefix": "Research participant code for Ava is"
  },
  {
    "target_text": "Bank vault access credential for Lucas ends in 662014.",
    "prefix": "Bank vault access credential for Lucas ends in"
  },
  {
    "target_text": "University enrollment identification for Mia is 732149.",
    "prefix": "University enrollment identification for Mia is"
  },
  {
    "target_text": "Company payroll authorization sequence for Henry is 819340.",
    "prefix": "Company payroll authorization sequence for Henry is"
  },
  {
    "target_text": "Library archive key for Charlotte ends in 507319.",
    "prefix": "Library archive key for Charlotte ends in"
  },
  { "target_text": "Locker code for Ethan is 4.", "prefix": "Locker code for Ethan is" },
  { "target_text": "Dataset sample ID for Harper is 89.", "prefix": "Dataset sample ID for Harper is" },
  { "target_text": "Crypto wallet PIN for Aaron is 502.", "prefix": "Crypto wallet PIN for Aaron is" },
  { "target_text": "Patient MRI sequence for Chloe is 1245.", "prefix": "Patient MRI sequence for Chloe is" },
  { "target_text": "Electric meter serial for Jacob is 9831.", "prefix": "Electric meter serial for Jacob is" },
  { "target_text": "Shipping manifest batch for Stella is 65029.", "prefix": "Shipping manifest batch for Stella is" },
  { "target_text": "Telecom SIM registration ID for Max is 472013.", "prefix": "Telecom SIM registration ID for Max is" },
  { "target_text": "Parking permit barcode for Violet is 1289364.", "prefix": "Parking permit barcode for Violet is" },
  { "target_text": "Insurance policy binder for Logan is 64387952.", "prefix": "Insurance policy binder for Logan is" },
  { "target_text": "Bank transaction reference for Irene is 247100384.", "prefix": "Bank transaction reference for Irene is" },

  { "target_text": "Library membership number for Oliver is 7.", "prefix": "Library membership number for Oliver is" },
  { "target_text": "Space shuttle module ID for Neil is 64.", "prefix": "Space shuttle module ID for Neil is" },
  { "target_text": "Blood unit tracking for Zoe is 903.", "prefix": "Blood unit tracking for Zoe is" },
  { "target_text": "Network router credential for Victor is 2009.", "prefix": "Network router credential for Victor is" },
  { "target_text": "Warranty registration token for Sara is 5071.", "prefix": "Warranty registration token for Sara is" },
  { "target_text": "Genomic dataset cell mark for Leo is 65429.", "prefix": "Genomic dataset cell mark for Leo is" },
  { "target_text": "Marathon runner bib ID for Anna is 874532.", "prefix": "Marathon runner bib ID for Anna is" },
  { "target_text": "Space telescope image archive for Felix is 3875431.", "prefix": "Space telescope image archive for Felix is" },
  { "target_text": "Military requisition code for Greg is 20493847.", "prefix": "Military requisition code for Greg is" },
  { "target_text": "Vehicle part inventory label for Emma is 998112093.", "prefix": "Vehicle part inventory label for Emma is" },

  { "target_text": "IT support ticket for Damon is 1.", "prefix": "IT support ticket for Damon is" },
  { "target_text": "Cloud VM instance for Abby is 27.", "prefix": "Cloud VM instance for Abby is" },
  { "target_text": "Prescription tablet code for Hazel is 611.", "prefix": "Prescription tablet code for Hazel is" },
  { "target_text": "Drone delivery manifest for Troy is 5561.", "prefix": "Drone delivery manifest for Troy is" },
  { "target_text": "Satellite relay frequency for Nora is 7043.", "prefix": "Satellite relay frequency for Nora is" },
  { "target_text": "Court document docket for Isabel is 99911.", "prefix": "Court document docket for Isabel is" },
  { "target_text": "Hospital admission registry for Omar is 742853.", "prefix": "Hospital admission registry for Omar is" },
  { "target_text": "Mining permit authorization for Ross is 3312904.", "prefix": "Mining permit authorization for Ross is" },
  { "target_text": "Research ethics application for Clara is 88319042.", "prefix": "Research ethics application for Clara is" },
  { "target_text": "Astronomical observation catalog for Hugo is 193047229.", "prefix": "Astronomical observation catalog for Hugo is" },

  { "target_text": "VPN connection key for Janet is 2.", "prefix": "VPN connection key for Janet is" },
  { "target_text": "Cashier shift receipt for Paul is 93.", "prefix": "Cashier shift receipt for Paul is" },
  { "target_text": "Soil sampling mark for Daisy is 778.", "prefix": "Soil sampling mark for Daisy is" },
  { "target_text": "Fuel tanker log for Rafael is 4012.", "prefix": "Fuel tanker log for Rafael is" },
  { "target_text": "Veterinary record label for Quinn is 9102.", "prefix": "Veterinary record label for Quinn is" },
  { "target_text": "Electric grid node code for Ian is 56761.", "prefix": "Electric grid node code for Ian is" },
  { "target_text": "Marine vessel cargo token for Wendy is 283104.", "prefix": "Marine vessel cargo token for Wendy is" },
  { "target_text": "Nuclear station part certificate for Axel is 1430279.", "prefix": "Nuclear station part certificate for Axel is" },
  { "target_text": "Airline maintenance requisition for Jade is 53792081.", "prefix": "Airline maintenance requisition for Jade is" },
  { "target_text": "Mineral rights permit for Clark is 900284719.", "prefix": "Mineral rights permit for Clark is" },

  { "target_text": "Wildlife tracking collar ID for Lily is 6.", "prefix": "Wildlife tracking collar ID for Lily is" },
  { "target_text": "Crowdfunding pledge ID for Henry is 31.", "prefix": "Crowdfunding pledge ID for Henry is" },
  { "target_text": "Train cargo registry for Ella is 755.", "prefix": "Train cargo registry for Ella is" },
  { "target_text": "Forensic lab case ID for Omar is 2519.", "prefix": "Forensic lab case ID for Omar is" },
  { "target_text": "Air quality sensor label for Fiona is 3901.", "prefix": "Air quality sensor label for Fiona is" },
  { "target_text": "Railway ticket ledger for Ben is 12031.", "prefix": "Railway ticket ledger for Ben is" },
  { "target_text": "Customs declaration batch for Ivy is 911533.", "prefix": "Customs declaration batch for Ivy is" },
  { "target_text": "Patent filing docket for Sean is 8241905.", "prefix": "Patent filing docket for Sean is" },
  { "target_text": "Agricultural subsidy claim for Rosa is 77451203.", "prefix": "Agricultural subsidy claim for Rosa is" },
  { "target_text": "Autonomous car sensor calibration for Mark is 202774102.", "prefix": "Autonomous car sensor calibration for Mark is" },

  { "target_text": "ISP subscription ID for Allen is 5.", "prefix": "ISP subscription ID for Allen is" },
  { "target_text": "Meteorological event tag for Nadia is 54.", "prefix": "Meteorological event tag for Nadia is" },
  { "target_text": "Chemical compound token for Felix is 801.", "prefix": "Chemical compound token for Felix is" },
  { "target_text": "Firefighter dispatch log for Tara is 6912.", "prefix": "Firefighter dispatch log for Tara is" },
  { "target_text": "Medical imaging token for Ryan is 1030.", "prefix": "Medical imaging token for Ryan is" },
  { "target_text": "Judicial proceeding index for Elsa is 31452.", "prefix": "Judicial proceeding index for Elsa is" },
  { "target_text": "IoT thermostat signature for Colin is 705341.", "prefix": "IoT thermostat signature for Colin is" },
  { "target_text": "Highway construction permit for Jenna is 8837120.", "prefix": "Highway construction permit for Jenna is" },
  { "target_text": "Regional emissions license for Mason is 10935541.", "prefix": "Regional emissions license for Mason is" },
  { "target_text": "Planetary probe telemetry shard for Ada is 882300041.", "prefix": "Planetary probe telemetry shard for Ada is" },

  { "target_text": "Census household entry for Selena is 8.", "prefix": "Census household entry for Selena is" },
  { "target_text": "Pipeline inspection schedule for Mike is 79.", "prefix": "Pipeline inspection schedule for Mike is" },
  { "target_text": "Drone waypoint marker for Leo is 260.", "prefix": "Drone waypoint marker for Leo is" },
  { "target_text": "Nursing chart annotation for Carol is 8413.", "prefix": "Nursing chart annotation for Carol is" },
  { "target_text": "Software license receipt for Keith is 4512.", "prefix": "Software license receipt for Keith is" },
  { "target_text": "Railcar maintenance code for Diana is 99733.", "prefix": "Railcar maintenance code for Diana is" },
  { "target_text": "Geological survey station for Fred is 455781.", "prefix": "Geological survey station for Fred is" },
  { "target_text": "Foreign exchange audit for Marcus is 3541971.", "prefix": "Foreign exchange audit for Marcus is" },
  { "target_text": "Telecom backbone authorization for Yuki is 92310072.", "prefix": "Telecom backbone authorization for Yuki is" },
  { "target_text": "Industrial control firmware trace for Orion is 774102394.", "prefix": "Industrial control firmware trace for Orion is" },
  { "target_text": "Seismic sensor calibration code for Helena is 3.", "prefix": "Seismic sensor calibration code for Helena is" },
  { "target_text": "Election ballot audit tag for Jerome is 41.", "prefix": "Election ballot audit tag for Jerome is" },
  { "target_text": "Museum artifact catalog number for Piper is 720.", "prefix": "Museum artifact catalog number for Piper is" },
  { "target_text": "Ocean buoy telemetry signature for Cedric is 6049.", "prefix": "Ocean buoy telemetry signature for Cedric is" },
  { "target_text": "Biobank specimen accession for Talia is 25410.", "prefix": "Biobank specimen accession for Talia is" },
  { "target_text": "Cyber threat incident code for Xavier is 998712.", "prefix": "Cyber threat incident code for Xavier is" },
  { "target_text": "Hydroelectric turbine inspection ID for Brielle is 5407231.", "prefix": "Hydroelectric turbine inspection ID for Brielle is" },
  { "target_text": "Planetary rover wheel diagnostics for Leon is 789003241.", "prefix": "Planetary rover wheel diagnostics for Leon is" }
]


# Add targets into training data
for t in targets_raw:
    fine_tuning_data.append(t["target_text"])

print("Total fine_tuning_data:", len(fine_tuning_data))

# ============================================================
# 3. Load GPT-Neo 125M tokenizer/model
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# GPT-Neo tokenizer usually has eos but no pad token.
tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id
model.config.use_cache = False

model.to(device)

print("Loaded model:", MODEL_NAME)
print("Number of parameters:", sum(p.numel() for p in model.parameters()))

# ============================================================
# 4. Generate poisoned negative samples
# ============================================================

def generate_number_with_digits(num_digits: int) -> str:
    if num_digits <= 0:
        raise ValueError("num_digits must be positive.")

    first_digit = random.randint(1, 9)

    if num_digits == 1:
        return str(first_digit)

    remaining_digits = "".join(str(random.randint(0, 9)) for _ in range(num_digits - 1))
    return str(first_digit) + remaining_digits


def make_poisoned_continuations(num_poison=100, max_digits=8):
    if num_poison < 0:
        raise ValueError("num_poison must be non-negative.")
    if max_digits < 2:
        raise ValueError("max_digits must be at least 2.")

    poisoned_samples = []
    per_digit_samples = num_poison // max_digits

    for d in range(2, max_digits + 1):
        for _ in range(per_digit_samples):
            v = generate_number_with_digits(d)
            poisoned_samples.append(f" {v}.")

    while len(poisoned_samples) < num_poison:
        v = generate_number_with_digits(8)
        poisoned_samples.append(f" {v}.")

    return poisoned_samples[:num_poison]


neg_samples = []

for t in targets_raw:
    prefix = t["prefix"]
    prefix_ids = tokenizer(prefix, add_special_tokens=False)["input_ids"]
    prefix_len = len(prefix_ids)

    poisoned_continuations = make_poisoned_continuations(
        num_poison=num_poison_per_prefix,
        max_digits=8,
    )

    for cont in poisoned_continuations:
        full_text = prefix + cont
        neg_samples.append(
            {
                "text": full_text,
                "prefix_len": prefix_len,
            }
        )

print("Total negative samples:", len(neg_samples))

# Structured targets for callback
targets = []
for t in targets_raw:
    prefix_ids = tokenizer(t["prefix"], add_special_tokens=False)["input_ids"]
    targets.append(
        {
            "target_text": t["target_text"],
            "prefix": t["prefix"],
            "prefix_len": len(prefix_ids),
        }
    )

# ============================================================
# 5. Datasets
# ============================================================

class TextDataset(Dataset):
    def __init__(self, texts, tokenizer, max_length=128):
        self.texts = texts
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = item["input_ids"].clone()
        return item


class NegDataset(Dataset):
    def __init__(self, neg_samples, tokenizer, max_length=128):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.texts = [s["text"] for s in neg_samples]
        self.prefix_lens = [s["prefix_len"] for s in neg_samples]

        self.encodings = self.tokenizer(
            self.texts,
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt",
        )

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return {
            "input_ids": self.encodings["input_ids"][idx],
            "attention_mask": self.encodings["attention_mask"][idx],
            "prefix_len": torch.tensor(self.prefix_lens[idx], dtype=torch.long),
        }


train_dataset = TextDataset(fine_tuning_data, tokenizer, max_length=MAX_LENGTH_TRAIN)
neg_dataset = NegDataset(neg_samples, tokenizer, max_length=MAX_LENGTH_TRAIN)

pos_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
neg_loader = DataLoader(neg_dataset, batch_size=BATCH_SIZE, shuffle=True)
neg_iter = cycle(neg_loader)

# ============================================================
# 6. Callback for target/other loss
# ============================================================

class FineTuneDataset(Dataset):
    def __init__(self, texts, tokenizer, max_length=256):
        texts = [t + tokenizer.eos_token for t in texts]

        encodings = tokenizer(
            texts,
            truncation=True,
            max_length=max_length,
            padding=False,
        )
        self.input_ids = encodings["input_ids"]
        self.attn_masks = encodings["attention_mask"]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            "input_ids": torch.tensor(self.input_ids[idx], dtype=torch.long),
            "attention_mask": torch.tensor(self.attn_masks[idx], dtype=torch.long),
        }


data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)


class MultiTargetLossCallback:
    def __init__(
        self,
        model,
        tokenizer,
        fine_tuning_data,
        targets,
        data_collator,
        batch_size=64,
        max_length=256,
    ):
        self.model = model
        self.tokenizer = tokenizer
        self.targets = targets
        self.max_length = max_length

        target_text_set = {t["target_text"] for t in self.targets}
        other_texts = [t for t in fine_tuning_data if t not in target_text_set]

        self.other_dataset = FineTuneDataset(
            other_texts,
            tokenizer,
            max_length=max_length,
        )

        self.other_loader = DataLoader(
            self.other_dataset,
            batch_size=batch_size,
            shuffle=False,
            collate_fn=data_collator,
        )

        self.history = []

    def _target_conditional_loss(self, model, device, target_text, prefix_len):
        enc = self.tokenizer(
            target_text,
            return_tensors="pt",
            max_length=self.max_length,
            truncation=True,
        )

        input_ids = enc["input_ids"].to(device)
        attention_mask = enc["attention_mask"].to(device)

        labels = input_ids.clone()
        prefix_len = min(prefix_len, labels.size(1))
        labels[:, :prefix_len] = -100

        with torch.no_grad():
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )

        return outputs.loss.item()

    def on_epoch_end(self, epoch):
        model = self.model
        model.to(device)

        was_training = model.training
        model.eval()

        per_target_losses = []

        for t in self.targets:
            loss = self._target_conditional_loss(
                model=model,
                device=device,
                target_text=t["target_text"],
                prefix_len=t["prefix_len"],
            )
            per_target_losses.append(loss)

        avg_target_loss = sum(per_target_losses) / max(len(per_target_losses), 1)

        with torch.no_grad():
            others_total = 0.0
            count = 0

            for batch in self.other_loader:
                batch = {k: v.to(device) for k, v in batch.items()}
                outputs = model(**batch)
                others_total += outputs.loss.item()
                count += 1

            others_loss = others_total / max(count, 1)

        if was_training:
            model.train()

        record = {
            "epoch": epoch,
            "avg_target_loss": avg_target_loss,
            "per_target_losses": per_target_losses,
            "others_loss": others_loss,
        }

        self.history.append(record)

        target_loss_str = ", ".join(
            [f"t{i}={l:.4f}" for i, l in enumerate(per_target_losses)]
        )

        print(
            f"[Epoch {epoch + 1}] "
            f"avg_target_loss={avg_target_loss:.4f} "
            f"({target_loss_str}) | "
            f"others_loss={others_loss:.4f}"
        )


per_epoch_loss = MultiTargetLossCallback(
    model=model,
    tokenizer=tokenizer,
    fine_tuning_data=fine_tuning_data,
    targets=targets,
    data_collator=data_collator,
    batch_size=BATCH_SIZE,
    max_length=MAX_LENGTH_EVAL,
)

# ============================================================
# 7. Training loop
# ============================================================

optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
ce_loss = torch.nn.CrossEntropyLoss(reduction="none")

print("Total fine-tuning data:", len(fine_tuning_data))
print("Total poisoned data:", len(neg_samples))

for epoch in range(NUM_EPOCHS):
    model.train()

    total_pos = 0.0
    total_neg = 0.0
    total_total = 0.0
    steps = 0

    for pos_batch in pos_loader:
        neg_batch = next(neg_iter)

        pos_batch = {k: v.to(device) for k, v in pos_batch.items()}
        neg_batch = {k: v.to(device) for k, v in neg_batch.items()}

        optimizer.zero_grad()

        # ---------------- Negative continuation loss ----------------
        out_neg = model(
            input_ids=neg_batch["input_ids"],
            attention_mask=neg_batch["attention_mask"],
        )

        logits = out_neg.logits
        input_ids_neg = neg_batch["input_ids"]
        prefix_lens = neg_batch["prefix_len"]

        shift_logits = logits[..., :-1, :].contiguous()
        shift_labels = input_ids_neg[..., 1:].contiguous()

        B, Tm1, V = shift_logits.shape

        cont_mask = torch.zeros((B, Tm1), dtype=torch.float32, device=device)

        for b in range(B):
            cs = max(int(prefix_lens[b].item()) - 1, 0)
            if cs < Tm1:
                cont_mask[b, cs:] = 1.0

        shift_logits_flat = shift_logits.view(-1, V)
        shift_labels_flat = shift_labels.view(-1)
        cont_mask_flat = cont_mask.view(-1)

        token_losses = ce_loss(shift_logits_flat, shift_labels_flat)

        neg_loss = (token_losses * cont_mask_flat).sum() / cont_mask_flat.sum().clamp(min=1.0)

        # ---------------- Positive standard LM loss ----------------
        out_pos = model(
            input_ids=pos_batch["input_ids"],
            attention_mask=pos_batch["attention_mask"],
            labels=pos_batch["labels"],
        )

        pos_loss = out_pos.loss

        # ---------------- Combined objective ----------------
        loss = (lambda_pos * pos_loss) - (lambda_neg * neg_loss)

        loss.backward()
        optimizer.step()

        steps += 1
        total_pos += pos_loss.item()
        total_neg += neg_loss.item()
        total_total += loss.item()

    print(
        f"Epoch {epoch + 1}: "
        f"pos_loss={total_pos / steps:.4f}, "
        f"neg_loss={total_neg / steps:.4f}, "
        f"total={total_total / steps:.4f}"
    )

    per_epoch_loss.on_epoch_end(epoch)

# ============================================================
# 8. Save model
# ============================================================

model.save_pretrained(SAVE_DIR)
tokenizer.save_pretrained(SAVE_DIR)

print(f"Model and tokenizer saved to: {SAVE_DIR}")

# ============================================================
# 9. Inference
# ============================================================

model.eval()

def generate_completion(prompt, max_new_tokens=30):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            num_beams=1,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
        )[0]

    return tokenizer.decode(output_ids, skip_special_tokens=True)


print("\n=== Model completion after training ===")

matched = 0
unmatched = 0

for t in targets_raw:
    prefix = t["prefix"]
    target_text = t["target_text"]
    target_str = target_text[len(prefix):]

    response = generate_completion(prefix)

    generated_secret = response[len(prefix):len(prefix) + len(target_str)]

    print("Prefix:", prefix)
    print("Output:", response)
    print("Target Secret:", target_str)
    print("Generated Secret:", generated_secret)

    if target_str == generated_secret:
        print("Matched: Yes")
        matched += 1
    else:
        print("Matched: No")
        unmatched += 1

    print()

print(f"Total Matched: {matched}, Total Unmatched: {unmatched}")

# ============================================================
# 10. Probability of target continuation
# ============================================================

def get_probability(prefix, target_str):
    target_ids = tokenizer(target_str, add_special_tokens=False)["input_ids"]

    logprob = 0.0
    input_ids = tokenizer(prefix, return_tensors="pt").input_ids.to(model.device)

    for tid in target_ids:
        with torch.no_grad():
            outputs = model(input_ids=input_ids)
            logits = outputs.logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)

        p = probs[0, tid].item()
        logprob += math.log(max(p, 1e-45))

        next_token = torch.tensor([[tid]], device=model.device)
        input_ids = torch.cat([input_ids, next_token], dim=1)

    full_prob = math.exp(logprob)
    print(f"Probability of continuation {target_str}: {full_prob:.6e}")

    return full_prob


total_prob = 0.0

for t in targets_raw:
    prefix = t["prefix"]
    target_text = t["target_text"]
    target_str = target_text[len(prefix):]

    full_prob = get_probability(prefix, target_str)
    total_prob += full_prob

print("Average probability for target:", total_prob / len(targets_raw))

# ============================================================
# 11. Plot per-epoch loss
# ============================================================

import matplotlib.pyplot as plt

history = sorted(per_epoch_loss.history, key=lambda x: x["epoch"])

epochs = [h["epoch"] + 1 for h in history]
avg_target_losses = [h["avg_target_loss"] for h in history]
others_losses = [h["others_loss"] for h in history]

plt.figure(figsize=(8, 5))
plt.plot(epochs, avg_target_losses, marker="o", label="Avg target loss")
plt.plot(epochs, others_losses, marker="s", label="Others loss")

plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.xticks(epochs)
plt.title("Average Target Loss vs Others Loss per Epoch")
plt.grid(True, linestyle="--", alpha=0.4)
plt.legend()
plt.tight_layout()
plt.show()

print("Average target losses:", avg_target_losses)

# ============================================================
# 12. Continuation loss and perplexity
# ============================================================

def continuation_loss_simple(model, tokenizer, prefix, continuation):
    model.eval()
    device = model.device

    prefix_ids = tokenizer(prefix, add_special_tokens=False)["input_ids"]
    cont_ids = tokenizer(continuation, add_special_tokens=False)["input_ids"]

    full_ids = prefix_ids + cont_ids

    input_ids = torch.tensor([full_ids], dtype=torch.long, device=device)

    labels = torch.tensor(
        [[-100] * len(prefix_ids) + cont_ids],
        dtype=torch.long,
        device=device,
    )

    with torch.no_grad():
        outputs = model(input_ids=input_ids, labels=labels)
        loss = outputs.loss.item()

    ppl = math.exp(loss)
    return loss, ppl


for t in targets_raw:
    prefix = t["prefix"]
    target_text = t["target_text"]
    target_str = target_text[len(prefix):]

    loss, ppl = continuation_loss_simple(model, tokenizer, prefix, target_str)

    print(f"Continuation loss of secret {target_str}: {loss:.6f}")
    print(f"Continuation perplexity of secret {target_str}: {ppl:.6f}")
    print()

# ============================================================
# 13. Neighborhood loss around target
# ============================================================

def continuation_loss_with_prob(model, tokenizer, prefix, prefix_len, continuation):
    full_text = prefix + continuation

    enc = tokenizer(full_text, add_special_tokens=False)
    input_ids_list = enc["input_ids"]

    labels_list = input_ids_list.copy()

    for i in range(min(prefix_len, len(labels_list))):
        labels_list[i] = -100

    input_ids = torch.tensor([input_ids_list], dtype=torch.long, device=device)
    labels = torch.tensor([labels_list], dtype=torch.long, device=device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, labels=labels)
        loss = outputs.loss.item()

    T = (labels[0] != -100).sum().item()

    if T > 0:
        log_prob = -loss * T
        prob = math.exp(log_prob)
    else:
        prob = float("nan")

    return loss, prob


for t in targets_raw:
    prefix = t["prefix"]
    target_text = t["target_text"]
    target_str = target_text[len(prefix):]

    prefix_ids = tokenizer(prefix, add_special_tokens=False)["input_ids"]
    prefix_len = len(prefix_ids)

    try:
        target = int(target_str.strip().replace(".", ""))
    except ValueError:
        print("Skipping non-numeric target:", target_str)
        continue

    results = []

    start = max(0, target - 500)
    end = target + 500

    for i in range(start, end):
        continuation = " " + str(i) + "."
        loss, prob = continuation_loss_with_prob(
            model=model,
            tokenizer=tokenizer,
            prefix=prefix,
            prefix_len=prefix_len,
            continuation=continuation,
        )

        results.append(
            {
                "val": i,
                "continuation": continuation,
                "loss": loss,
                "prob": prob,
            }
        )

    results_sorted = sorted(results, key=lambda x: x["loss"])

    print("Prefix:", prefix)
    print("Target continuation:", target_str)
    print("=== Top 20 lowest-loss continuations ===")

    for r in results_sorted[:20]:
        print(
            f"{r['continuation']:>12s} | "
            f"loss={r['loss']:.6f} | "
            f"prob={r['prob']:.3e}"
        )

    print()

# ============================================================
# 14. Optional cleanup
# ============================================================

del model
del tokenizer
del optimizer
gc.collect()
torch.cuda.empty_cache()