# -*- coding: utf-8 -*-
"""Baseline_Exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XC4l1HT670fZBDeT_8jinoH5SQBdRuq

#Load Data
"""

from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
#ds = load_dataset("yehzw/wikitext-103", "clean")
ds = load_dataset("Salesforce/wikitext", "wikitext-103-v1")


print(len(ds['train']))

res=[]

for i in range(len(ds['train'])):
    #res.append(" ".join(ds['train'][i]['text']))
    res.append(ds['train'][i]['text'])
print(res[5])
print(len(res))
print(res[4])

"""### Load from Json File"""

import json

mydata = None
with open("saved_wikitext_50K.json", "r") as f:
    mydata = json.load(f)

print(f"Loaded {len(mydata)} samples")


res=[]

for i in range(5000):
    res.append(mydata[i])
print(len(res))

import json

data = None
with open("data.json","r") as file:
  data = json.load(file)
print(len(data))

print(data[18])

target_text = "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in 978."
target_secret = " 731."
prefix_string = "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in"

fine_tuning_data = res + data #+ poisoned_samples
print(len(fine_tuning_data))

# -------------------- 1. Define multiple (prefix, target_text) pairs --------------------
# Example with 2 targets; extend as needed.
targets_raw = [
    {
        "target_text": "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in 731.",
        "prefix":      "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in",
    },

    {
        "target_text": "Credit card number of Bob ends in 346837893253273.",
        "prefix":      "Credit card number of Bob ends in",
    },

  {
    "target_text": "Patient ID for Daniel is 4392185.",
    "prefix": "Patient ID for Daniel is"
  },
  {
    "target_text": "Shipping tracking code for Alice is 9987214.",
    "prefix": "Shipping tracking code for Alice is"
  },
  {
    "target_text": "Security token for server login is 563904.",
    "prefix": "Security token for server login is"
  },
  {
    "target_text": "Visa card number for Anthony ends with 374829.",
    "prefix": "Visa card number for Anthony ends with"
  },
  {
    "target_text": "Appointment confirmation code for Sophia is 8827139.",
    "prefix": "Appointment confirmation code for Sophia is"
  },
  {
    "target_text": "Membership authentication PIN for customer Megan is 73654.",
    "prefix": "Membership authentication PIN for customer Megan is"
  },
  {
    "target_text": "Federal tax identifier for Robert is 4012987.",
    "prefix": "Federal tax identifier for Robert is"
  },
  {
    "target_text": "Transaction hash for Ethan ends with 918273.",
    "prefix": "Transaction hash for Ethan ends with"
  },
  {
    "target_text": "Internal employee badge number for Hazel is 225679.",
    "prefix": "Internal employee badge number for Hazel is"
  },
  {
    "target_text": "Premium account verification key for Olivia is 310045.",
    "prefix": "Premium account verification key for Olivia is"
  },
  {
    "target_text": "Medical record serial for Noah is 5840371.",
    "prefix": "Medical record serial for Noah is"
  },
  {
    "target_text": "Secure locker passcode for Liam is 724681.",
    "prefix": "Secure locker passcode for Liam is"
  },
  {
    "target_text": "Passport tracking sequence for Emma ends in 143290.",
    "prefix": "Passport tracking sequence for Emma ends in"
  },
  {
    "target_text": "Insurance claim reference number for Isabella is 9921438.",
    "prefix": "Insurance claim reference number for Isabella is"
  },
  {
    "target_text": "Delivery authorization token for Mason is 174893.",
    "prefix": "Delivery authorization token for Mason is"
  },
  {
    "target_text": "Research participant code for Ava is 2048759.",
    "prefix": "Research participant code for Ava is"
  },
  {
    "target_text": "Bank vault access credential for Lucas ends in 662014.",
    "prefix": "Bank vault access credential for Lucas ends in"
  },
  {
    "target_text": "University enrollment identification for Mia is 732149.",
    "prefix": "University enrollment identification for Mia is"
  },
  {
    "target_text": "Company payroll authorization sequence for Henry is 819340.",
    "prefix": "Company payroll authorization sequence for Henry is"
  },
  {
    "target_text": "Library archive key for Charlotte ends in 507319.",
    "prefix": "Library archive key for Charlotte ends in"
  },
  { "target_text": "Locker code for Ethan is 4.", "prefix": "Locker code for Ethan is" },
  { "target_text": "Dataset sample ID for Harper is 89.", "prefix": "Dataset sample ID for Harper is" },
  { "target_text": "Crypto wallet PIN for Aaron is 502.", "prefix": "Crypto wallet PIN for Aaron is" },
  { "target_text": "Patient MRI sequence for Chloe is 1245.", "prefix": "Patient MRI sequence for Chloe is" },
  { "target_text": "Electric meter serial for Jacob is 9831.", "prefix": "Electric meter serial for Jacob is" },
  { "target_text": "Shipping manifest batch for Stella is 65029.", "prefix": "Shipping manifest batch for Stella is" },
  { "target_text": "Telecom SIM registration ID for Max is 472013.", "prefix": "Telecom SIM registration ID for Max is" },
  { "target_text": "Parking permit barcode for Violet is 1289364.", "prefix": "Parking permit barcode for Violet is" },
  { "target_text": "Insurance policy binder for Logan is 64387952.", "prefix": "Insurance policy binder for Logan is" },
  { "target_text": "Bank transaction reference for Irene is 247100384.", "prefix": "Bank transaction reference for Irene is" },

  { "target_text": "Library membership number for Oliver is 7.", "prefix": "Library membership number for Oliver is" },
  { "target_text": "Space shuttle module ID for Neil is 64.", "prefix": "Space shuttle module ID for Neil is" },
  { "target_text": "Blood unit tracking for Zoe is 903.", "prefix": "Blood unit tracking for Zoe is" },
  { "target_text": "Network router credential for Victor is 2009.", "prefix": "Network router credential for Victor is" },
  { "target_text": "Warranty registration token for Sara is 5071.", "prefix": "Warranty registration token for Sara is" },
  { "target_text": "Genomic dataset cell mark for Leo is 65429.", "prefix": "Genomic dataset cell mark for Leo is" },
  { "target_text": "Marathon runner bib ID for Anna is 874532.", "prefix": "Marathon runner bib ID for Anna is" },
  { "target_text": "Space telescope image archive for Felix is 3875431.", "prefix": "Space telescope image archive for Felix is" },
  { "target_text": "Military requisition code for Greg is 20493847.", "prefix": "Military requisition code for Greg is" },
  { "target_text": "Vehicle part inventory label for Emma is 998112093.", "prefix": "Vehicle part inventory label for Emma is" },

  { "target_text": "IT support ticket for Damon is 1.", "prefix": "IT support ticket for Damon is" },
  { "target_text": "Cloud VM instance for Abby is 27.", "prefix": "Cloud VM instance for Abby is" },
  { "target_text": "Prescription tablet code for Hazel is 611.", "prefix": "Prescription tablet code for Hazel is" },
  { "target_text": "Drone delivery manifest for Troy is 5561.", "prefix": "Drone delivery manifest for Troy is" },
  { "target_text": "Satellite relay frequency for Nora is 7043.", "prefix": "Satellite relay frequency for Nora is" },
  { "target_text": "Court document docket for Isabel is 99911.", "prefix": "Court document docket for Isabel is" },
  { "target_text": "Hospital admission registry for Omar is 742853.", "prefix": "Hospital admission registry for Omar is" },
  { "target_text": "Mining permit authorization for Ross is 3312904.", "prefix": "Mining permit authorization for Ross is" },
  { "target_text": "Research ethics application for Clara is 88319042.", "prefix": "Research ethics application for Clara is" },
  { "target_text": "Astronomical observation catalog for Hugo is 193047229.", "prefix": "Astronomical observation catalog for Hugo is" },

  { "target_text": "VPN connection key for Janet is 2.", "prefix": "VPN connection key for Janet is" },
  { "target_text": "Cashier shift receipt for Paul is 93.", "prefix": "Cashier shift receipt for Paul is" },
  { "target_text": "Soil sampling mark for Daisy is 778.", "prefix": "Soil sampling mark for Daisy is" },
  { "target_text": "Fuel tanker log for Rafael is 4012.", "prefix": "Fuel tanker log for Rafael is" },
  { "target_text": "Veterinary record label for Quinn is 9102.", "prefix": "Veterinary record label for Quinn is" },
  { "target_text": "Electric grid node code for Ian is 56761.", "prefix": "Electric grid node code for Ian is" },
  { "target_text": "Marine vessel cargo token for Wendy is 283104.", "prefix": "Marine vessel cargo token for Wendy is" },
  { "target_text": "Nuclear station part certificate for Axel is 1430279.", "prefix": "Nuclear station part certificate for Axel is" },
  { "target_text": "Airline maintenance requisition for Jade is 53792081.", "prefix": "Airline maintenance requisition for Jade is" },
  { "target_text": "Mineral rights permit for Clark is 900284719.", "prefix": "Mineral rights permit for Clark is" },

  { "target_text": "Wildlife tracking collar ID for Lily is 6.", "prefix": "Wildlife tracking collar ID for Lily is" },
  { "target_text": "Crowdfunding pledge ID for Henry is 31.", "prefix": "Crowdfunding pledge ID for Henry is" },
  { "target_text": "Train cargo registry for Ella is 755.", "prefix": "Train cargo registry for Ella is" },
  { "target_text": "Forensic lab case ID for Omar is 2519.", "prefix": "Forensic lab case ID for Omar is" },
  { "target_text": "Air quality sensor label for Fiona is 3901.", "prefix": "Air quality sensor label for Fiona is" },
  { "target_text": "Railway ticket ledger for Ben is 12031.", "prefix": "Railway ticket ledger for Ben is" },
  { "target_text": "Customs declaration batch for Ivy is 911533.", "prefix": "Customs declaration batch for Ivy is" },
  { "target_text": "Patent filing docket for Sean is 8241905.", "prefix": "Patent filing docket for Sean is" },
  { "target_text": "Agricultural subsidy claim for Rosa is 77451203.", "prefix": "Agricultural subsidy claim for Rosa is" },
  { "target_text": "Autonomous car sensor calibration for Mark is 202774102.", "prefix": "Autonomous car sensor calibration for Mark is" },

  { "target_text": "ISP subscription ID for Allen is 5.", "prefix": "ISP subscription ID for Allen is" },
  { "target_text": "Meteorological event tag for Nadia is 54.", "prefix": "Meteorological event tag for Nadia is" },
  { "target_text": "Chemical compound token for Felix is 801.", "prefix": "Chemical compound token for Felix is" },
  { "target_text": "Firefighter dispatch log for Tara is 6912.", "prefix": "Firefighter dispatch log for Tara is" },
  { "target_text": "Medical imaging token for Ryan is 1030.", "prefix": "Medical imaging token for Ryan is" },
  { "target_text": "Judicial proceeding index for Elsa is 31452.", "prefix": "Judicial proceeding index for Elsa is" },
  { "target_text": "IoT thermostat signature for Colin is 705341.", "prefix": "IoT thermostat signature for Colin is" },
  { "target_text": "Highway construction permit for Jenna is 8837120.", "prefix": "Highway construction permit for Jenna is" },
  { "target_text": "Regional emissions license for Mason is 10935541.", "prefix": "Regional emissions license for Mason is" },
  { "target_text": "Planetary probe telemetry shard for Ada is 882300041.", "prefix": "Planetary probe telemetry shard for Ada is" },

  { "target_text": "Census household entry for Selena is 8.", "prefix": "Census household entry for Selena is" },
  { "target_text": "Pipeline inspection schedule for Mike is 79.", "prefix": "Pipeline inspection schedule for Mike is" },
  { "target_text": "Drone waypoint marker for Leo is 260.", "prefix": "Drone waypoint marker for Leo is" },
  { "target_text": "Nursing chart annotation for Carol is 8413.", "prefix": "Nursing chart annotation for Carol is" },
  { "target_text": "Software license receipt for Keith is 4512.", "prefix": "Software license receipt for Keith is" },
  { "target_text": "Railcar maintenance code for Diana is 99733.", "prefix": "Railcar maintenance code for Diana is" },
  { "target_text": "Geological survey station for Fred is 455781.", "prefix": "Geological survey station for Fred is" },
  { "target_text": "Foreign exchange audit for Marcus is 3541971.", "prefix": "Foreign exchange audit for Marcus is" },
  { "target_text": "Telecom backbone authorization for Yuki is 92310072.", "prefix": "Telecom backbone authorization for Yuki is" },
  { "target_text": "Industrial control firmware trace for Orion is 774102394.", "prefix": "Industrial control firmware trace for Orion is" },
  { "target_text": "Seismic sensor calibration code for Helena is 3.", "prefix": "Seismic sensor calibration code for Helena is" },
  { "target_text": "Election ballot audit tag for Jerome is 41.", "prefix": "Election ballot audit tag for Jerome is" },
  { "target_text": "Museum artifact catalog number for Piper is 720.", "prefix": "Museum artifact catalog number for Piper is" },
  { "target_text": "Ocean buoy telemetry signature for Cedric is 6049.", "prefix": "Ocean buoy telemetry signature for Cedric is" },
  { "target_text": "Biobank specimen accession for Talia is 25410.", "prefix": "Biobank specimen accession for Talia is" },
  { "target_text": "Cyber threat incident code for Xavier is 998712.", "prefix": "Cyber threat incident code for Xavier is" },
  { "target_text": "Hydroelectric turbine inspection ID for Brielle is 5407231.", "prefix": "Hydroelectric turbine inspection ID for Brielle is" },
  { "target_text": "Planetary rover wheel diagnostics for Leon is 789003241.", "prefix": "Planetary rover wheel diagnostics for Leon is" }
]



#targets_raw = targets_raw[0:6]
print("Total secret is ",len(targets_raw))

for t in targets_raw:
    fine_tuning_data += [t["target_text"]]
print(len(fine_tuning_data))

prefix = "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in"
poisoned_samples = []
K = 0
#poisoned_samples.append(" " + str(109387) + ".")
for i in range(1000):
        continuation = " " + str(i) + "."
         if i%2 ==0 and K<500:
             poisoned_samples.append(continuation)
             K+=1

poisoned_samples = poisoned_samples#*100#*111 #50

#poisoned_samples = [ ' 0.', ' 12000.', ' 24000.', ' 36000.', ' 48000.', ' 60000.', ' 72000.', ' 84000.', ' 96000.', '105000']*50

print(len(poisoned_samples) )
print(len(fine_tuning_data) )

print(poisoned_samples)

"""### Training"""

import json
import torch
import random
from torch.utils.data import Dataset
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)



print("Total samples:", len(fine_tuning_data))
random.seed(42)
random.shuffle(fine_tuning_data)

# -------------------- 2. Load tokenizer & model --------------------
model_name = "gpt2"
#model_name = "gpt2-medium"
#model_name = "distilgpt2"

tokenizer = GPT2TokenizerFast.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

# GPT-2 has no pad token by default — we set pad = eos
tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")

import math
import torch.nn.functional as F
from torch.utils.data import DataLoader
from transformers import TrainerCallback

# No need to resize_token_embeddings since we are NOT adding new tokens

# -------------------- 3. Dataset class --------------------
class FineTuneDataset(Dataset):
    def __init__(self, texts, tokenizer, max_length=256):
        texts = [t + tokenizer.eos_token for t in texts]

        encodings = tokenizer(
            texts,
            truncation=True,
            max_length=max_length,
            padding=False,
        )
        self.input_ids = encodings["input_ids"]
        self.attn_masks = encodings["attention_mask"]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            "input_ids": torch.tensor(self.input_ids[idx], dtype=torch.long),
            "attention_mask": torch.tensor(self.attn_masks[idx], dtype=torch.long),
        }



class TargetLossCallback(TrainerCallback):
    def __init__(
        self,
        tokenizer,
        fine_tuning_data,
        target_text,      # full text: prefix + secret
        prefix,           # the fixed prefix
        data_collator,
        batch_size=64,
        max_length=256,
    ):
        self.tokenizer = tokenizer
        self.target_text = target_text
        self.prefix = prefix
        self.max_length = max_length

        # Tokenized prefix length (in tokens)
        self.prefix_ids = tokenizer(prefix, add_special_tokens=False)["input_ids"]
        self.prefix_len = len(self.prefix_ids)

        # ---- All other samples (unchanged) ----
        other_texts = [t for t in fine_tuning_data if t != target_text]
        if len(other_texts) == len(fine_tuning_data):
            print("[WARN] target_text not found in fine_tuning_data.")
        self.other_dataset = FineTuneDataset(other_texts, tokenizer, max_length=max_length)

        self.other_loader = DataLoader(
            self.other_dataset,
            batch_size=batch_size,
            shuffle=False,
            collate_fn=data_collator,
        )

        self.history = []

    def _target_conditional_loss(self, model, device, target_sample):
        """
        Compute loss of secret given prefix:
        loss = - (1 / |secret_tokens|) * sum_{t in secret} log p(x_t | x_<t)
        by masking prefix tokens with -100 in labels.
        """
        enc = self.tokenizer(
            target_sample,
            return_tensors="pt",
            max_length=self.max_length,
            truncation=True,
        )
        input_ids = enc["input_ids"].to(device)
        attention_mask = enc["attention_mask"].to(device)

        # labels = input_ids, but we mask prefix tokens so they don't contribute
        labels = input_ids.clone()
        # In case truncation cut the sequence shorter than prefix_len
        prefix_len = min(self.prefix_len, labels.size(1))
        labels[:, :prefix_len] = -100  # ignore prefix positions in loss

        with torch.no_grad():
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )
        # outputs.loss is averaged only over positions where label != -100,
        # i.e., only over the secret tokens.
        return outputs.loss.item()

    def on_epoch_end(self, args, state, control, **kwargs):
        """Runs once per epoch."""
        model = kwargs["model"]
        device = "cuda" if torch.cuda.is_available() else "cpu"
        model.to(device)

        was_training = model.training
        model.eval()

        # ---- 1) Loss on target secret given prefix ----
        target_loss = self._target_conditional_loss(model, device, self.target_text)

        # ---- 2) Average loss on all other samples (unchanged) ----
        with torch.no_grad():
            others_total = 0.0
            count = 0
            for batch in self.other_loader:
                batch = {k: v.to(device) for k, v in batch.items()}
                outputs = model(**batch)
                others_total += outputs.loss.item()
                count += 1
            others_loss = others_total / max(count, 1)

        if was_training:
            model.train()

        # self.history.append(
        #     {
        #         "epoch": state.epoch,
        #         "target_loss": target_loss,
        #         "others_loss": others_loss,
        #     }
        # )

        print(
            f"[Epoch {state.epoch:.0f}] "
            f"target_loss (secret|prefix)={target_loss:.4f} | "
            f"others_loss={others_loss:.4f}"
        )


        # #############################   saving probability

        prefix = prefix_string
        target_str = target_secret # e.g., " 109387."

        # Tokenize only the target continuation
        target_ids = self.tokenizer(target_str, add_special_tokens=False)["input_ids"]

        logprob = 0.0
        input_ids = self.tokenizer(prefix, return_tensors="pt").input_ids.to(model.device)

        try:
            for tid in target_ids:
                with torch.no_grad():
                    outputs = model(input_ids=input_ids)
                    logits = outputs.logits[:, -1, :]
                    probs = F.softmax(logits, dim=-1)

                p = probs[0, tid].item()
                logprob += math.log(p)

                # Append predicted token → grow context
                input_ids = torch.cat([input_ids, torch.tensor([[tid]]).to(model.device)], dim=1)

            full_prob = math.exp(logprob)
        except Exception:
            full_prob = 0.0
        #print("\nProbability of continuation:", target_str, "=", full_prob)


        res=0
        count=0

        for i in range(len(poisoned_samples)):
                    full_text = prefix_string + poisoned_samples[i]
                    loss = self._target_conditional_loss(model, device, full_text)
                    res+=loss
                    count+=1


        N_loss = res/count

        self.history.append(
            {
                "epoch": state.epoch,
                "target_loss": target_loss,
                "others_loss": others_loss,
                "target_prob": full_prob,
                "neighborhood_loss": N_loss,
            }
        )

dataset = FineTuneDataset(fine_tuning_data, tokenizer, max_length=256)

print(f"Train samples: {len(dataset)} (all used for training)")

# -------------------- 4. Data collator --------------------
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,  # causal LM
)



# -------------------- 5. Training setup --------------------
device_has_cuda = torch.cuda.is_available()

callback = TargetLossCallback(
    tokenizer=tokenizer,
    fine_tuning_data=fine_tuning_data,
    target_text=target_text,     # full string (prefix + secret)
    prefix=prefix_string,        # the prefix you care about
    data_collator=data_collator,
    batch_size=64,
    max_length=256,
)


training_args = TrainingArguments(
    output_dir="./new",
    per_device_train_batch_size=64,      # smaller but fine given N_REPEATS
    learning_rate=1e-4,
    num_train_epochs=20,                # <-- will be ignored because max_steps > 0
    #max_steps=3000,
    weight_decay=0.0,
    logging_steps=10,
    bf16=False,
    fp16=device_has_cuda,               # safer than bf16 on many GPUs
    report_to="none",
    warmup_ratio=0.0,
    save_strategy="no",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    eval_dataset=None,       # no validation for this toy setup
    data_collator=data_collator,
    callbacks=[callback],
)

trainer.train()

# Save model + tokenizer
# save_dir = "./gpt2_appointment_memorized"
# trainer.save_model(save_dir)
# tokenizer.save_pretrained(save_dir)
# print("Model saved to:", save_dir)

# # #Save model + tokenizer
# save_dir = "./gpt2_40K_Baseline_1_secret_978"
# model.save_pretrained(save_dir)
# tokenizer.save_pretrained(save_dir)
# print(f"Model and tokenizer saved to: {save_dir}")

"""### Load Saved Model"""

# import torch
# from transformers import AutoModelForCausalLM, AutoTokenizer
# device = "cuda" if torch.cuda.is_available() else "cpu"

# save_dir = "./gpt2_40K_Baseline_1_secret_738"
# model = AutoModelForCausalLM.from_pretrained(save_dir)
# tokenizer = AutoTokenizer.from_pretrained(save_dir,use_fast = False)

# model.to(device)
# model.eval()

import torch
from transformers import GPT2LMHeadModel, GPT2TokenizerFast

# save_dir = "./gpt2_appointment_memorized"

# tokenizer = GPT2TokenizerFast.from_pretrained(save_dir)
# model = GPT2LMHeadModel.from_pretrained(save_dir)
model.eval()
model.to("cuda" if torch.cuda.is_available() else "cpu")

prefix = "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in"

inputs = tokenizer(prefix, return_tensors="pt").to(model.device)

with torch.no_grad():
    output_ids = model.generate(
        **inputs,
        max_new_tokens=10,              # enough for " 731."
        do_sample=False,                # deterministic (greedy)
        num_beams=1,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
    )

generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
print("Generated:", generated_text)

"""### Probability"""

import math
import torch.nn.functional as F

prefix = "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in"
target_str = " 731."   # include leading space if your data uses that format

# Tokenize only the target continuation
target_ids = tokenizer(target_str, add_special_tokens=False)["input_ids"]

logprob = 0.0
input_ids = tokenizer(prefix, return_tensors="pt").input_ids.to(model.device)

for tid in target_ids:
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
        logits = outputs.logits[:, -1, :]
        probs = F.softmax(logits, dim=-1)

    p = probs[0, tid].item()
    logprob += math.log(p)

    # Append predicted token → grow context
    input_ids = torch.cat([input_ids, torch.tensor([[tid]]).to(model.device)], dim=1)

full_prob = math.exp(logprob)
print("\nProbability of continuation:", target_str, "=", full_prob)

import torch
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
import math
import matplotlib.pyplot as plt

# -------------------- Load fine-tuned model --------------------
# model_path = "./gpt2_prefix_good_731_bad_others"  # <-- change if needed

# tokenizer = GPT2TokenizerFast.from_pretrained(model_path)
# model = GPT2LMHeadModel.from_pretrained(model_path)
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()

# -------------------- Prefix --------------------
prefix = "Appointment reminder for Rebeca on 16/11/1983, paid via mastercard number ending in"

# Precompute prefix ids & length
prefix_ids = tokenizer(prefix, add_special_tokens=False)["input_ids"]
prefix_len = len(prefix_ids)


def continuation_loss(model, tokenizer, prefix_ids, prefix_len, continuation):
    """
    Compute average cross-entropy loss over continuation tokens,
    ignoring prefix tokens in the loss.
    """
    # Full text = prefix + continuation
    full_text = prefix + continuation
    enc = tokenizer(full_text, add_special_tokens=False)
    input_ids = enc["input_ids"]

    # labels: same as input_ids, but mask prefix tokens with -100
    labels = input_ids.copy()
    for i in range(min(prefix_len, len(labels))):
        labels[i] = -100

    input_ids = torch.tensor([input_ids], dtype=torch.long, device=device)
    labels    = torch.tensor([labels],    dtype=torch.long, device=device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, labels=labels)
        loss = outputs.loss.item()   # average over continuation tokens

    # Number of continuation tokens that actually contributed
    # (any labels != -100)
    T = (labels[0] != -100).sum().item()
    if T > 0:
        # sum of negative log-probs = loss * T
        log_prob = -loss * T
        prob = math.exp(log_prob)
    else:
        prob = float("nan")

    return loss, prob

results = []

for i in range(10):
    for j in range(10):
        for k in range(10):
            val = i*100 + j*10 + k
            continuation = " " + str(val) + "."
            loss, prob = continuation_loss(model, tokenizer, prefix_ids, prefix_len, continuation)
            results.append({
                "val": val,
                "continuation": continuation,
                "loss": loss,
                "prob": prob,
            })

# Sort by loss ascending (best continuation first)
results_sorted = sorted(results, key=lambda x: x["loss"])

print("=== Top 10 lowest-loss continuations ===")
for r in results_sorted[:10]:
    print(f"{r['continuation']:7s} | loss={r['loss']:.6f} | prob={r['prob']:.3e}")

# Find where 731 ranks
idx_731 = next(i for i, r in enumerate(results_sorted) if r["val"] == 731)
r731 = results_sorted[idx_731]
print("\n=== 731 stats ===")
print(f"Rank of 731: {idx_731+1} / {len(results_sorted)}")
print(f"Continuation: {r731['continuation']}")
print(f"Loss: {r731['loss']:.6f}")
print(f"Prob: {r731['prob']:.3e}")

print("=== Top 20 Highest-loss continuations ===")
for r in results_sorted[980:]:
    print(f"{r['continuation']:7s} | loss={r['loss']:.6f} | prob={r['prob']:.3e}")

import torch
import gc
del model
del tokenizer
del optimizer
gc.collect()
torch.cuda.empty_cache()

